export const WatchItems = [
  {
    title: "CW0001 CUSTOM WATCH",
    price: "12,000",
    imageOne: require('./WatchImg/watch1/watch1.jpg'),
    imageTwo: require('./WatchImg/watch1/watch5.jpg'),
  },
  {
    title: "CW0002 CUSTOM WATCH",
    price: "12,000",
    imageOne: require('./WatchImg/watch2/watch1.jpg'),
    imageTwo: require('./WatchImg/watch2/watch2.jpg'),
  },
  {
    title: "CW0003 CUSTOM WATCH",
    price: "12,000",
    imageOne: require('./WatchImg/watch3/watch1.jpg'),
    imageTwo: require('./WatchImg/watch3/watch2.jpg'),
  },
  {
    title: "CW0004 CUSTOM WATCH",
    price: "12,000",
    imageOne: require('./WatchImg/watch4/watch1.jpg'),
    imageTwo: require('./WatchImg/watch4/watch2.jpg'),
  },
  {
    title: "CW0005 CUSTOM WATCH",
    price: "12,000",
    imageOne: require('./WatchImg/watch5/watch1.jpg'),
    imageTwo: require('./WatchImg/watch5/watch2.jpg'),
  },
  {
    title: "CW0006 CUSTOM WATCH",
    price: "12,000",
    imageOne: require('./WatchImg/watch6/watch1.jpg'),
    imageTwo: require('./WatchImg/watch6/watch2.jpg'),
  },
  {
    title: "CW0007 CUSTOM WATCH",
    price: "12,000",
    imageOne: require('./WatchImg/watch7/watch1.jpg'),
    imageTwo: require('./WatchImg/watch7/watch2.jpg'),
  },
  {
    title: "CW0008 CUSTOM WATCH",
    price: "12,000",
    imageOne: require('./WatchImg/watch8/watch1.jpg'),
    imageTwo: require('./WatchImg/watch8/watch2.jpg'),
  },
  {
    title: "CW0009 CUSTOM WATCH",
    price: "12,000",
    imageOne: require('./WatchImg/watch9/watch1.jpg'),
    imageTwo: require('./WatchImg/watch9/watch2.jpg'),
  },
  {
    title: "CW00010 CUSTOM WATCH",
    price: "12,000",
    imageOne: require('./WatchImg/watch10/watch1.jpg'),
    imageTwo: require('./WatchImg/watch10/watch2.jpg'),
  },
  {
    title: "CW00011 CUSTOM WATCH",
    price: "12,000",
    imageOne: require('./WatchImg/watch11/watch1.jpg'),
    imageTwo: require('./WatchImg/watch11/watch2.jpg'),
  },
  {
    title: "CW00012 CUSTOM WATCH",
    price: "12,000",
    imageOne: require('./WatchImg/watch12/watch1.jpg'),
    imageTwo: require('./WatchImg/watch12/watch2.jpg'),
  },
  {
    title: "CW00013 CUSTOM WATCH",
    price: "12,000",
    imageOne: require('./WatchImg/watch13/watch1.jpg'),
    imageTwo: require('./WatchImg/watch13/watch2.jpg'),
  },
  {
    title: "CW00014 CUSTOM WATCH",
    price: "12,000",
    imageOne: require('./WatchImg/watch14/watch1.jpg'),
    imageTwo: require('./WatchImg/watch14/watch2.jpg'),
  },
  {
    title: "CW00015 CUSTOM WATCH",
    price: "12,000",
    imageOne: require('./WatchImg/watch15/watch1.jpg'),
    imageTwo: require('./WatchImg/watch15/watch2.jpg'),
  },
  {
    title: "CW00016 CUSTOM WATCH",
    price: "12,000",
    imageOne: require('./WatchImg/watch16/watch1.jpg'),
    imageTwo: require('./WatchImg/watch16/watch2.jpg'),
  },
  {
    title: "CW00017 CUSTOM WATCH",
    price: "12,000",
    imageOne: require('./WatchImg/watch17/watch1.jpg'),
    imageTwo: require('./WatchImg/watch17/watch2.jpg'),
  },
  {
    title: "CW00018 CUSTOM WATCH",
    price: "12,000",
    imageOne: require('./WatchImg/watch18/watch1.jpg'),
    imageTwo: require('./WatchImg/watch18/watch2.jpg'),
  },
  {
    title: "CW00019 CUSTOM WATCH",
    price: "12,000",
    imageOne: require('./WatchImg/watch19/watch1.jpg'),
    imageTwo: require('./WatchImg/watch19/watch2.jpg'),
  },
];